language: python
python:
- '3.6'

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install pipenv
  - pipenv install

script:
- python manage.py test
