# Generated by Django 2.2 on 2019-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_platform',
            field=models.CharField(default='app', max_length=50),
        ),
    ]
