# Generated by Django 2.2 on 2019-04-11 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20190411_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=False, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]