# Generated by Django 2.2 on 2019-04-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190415_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='articles.Article'),
        ),
    ]
