# Generated by Django 2.2 on 2019-04-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_readingstats'),
        ('articles', '0004_articlerating'),
    ]

    operations = [
    ]
