# Generated by Django 2.2 on 2019-04-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20190416_1226'),
        ('articles', '0005_bookmark'),
    ]

    operations = [
    ]
